"""Application-wide constants.

These values are fixed at build time and never sourced from user input or LLM output.
"""

from __future__ import annotations

AI_ANALYSIS_DISCLAIMER: str = (
    "This analysis is generated by an AI system using publicly available market data "
    "and news sources. It is provided for informational purposes only and does not "
    "constitute financial advice, investment recommendations, or an offer to buy or "
    "sell any securities. Always conduct your own research and consult a qualified "
    "financial professional before making investment decisions. Past performance is "
    "not indicative of future results."
)

SCHEMA_VERSION: str = "1.0"
